# Borders
default_border              pixel 0
default_floating_border     pixel 3
# hide_edge_borders           smart

# Colors
# client.focused   #524f67 #524f67 #e0def4 #26233a #26233a
# client.unfocused #191724 #191724 #e0def4 #191724 #191724

# Bars
bar {
  position bottom
  status_command i3status

  colors {
    background #191724
    # Syntax: <border> <background> <text>
    focused_workspace  #286983 #286983 #ffffff
    active_workspace   #286983 #286983 #ffffff
    inactive_workspace #191724 #191724 #ffffff
    urgent_workspace   #b4637a #b4637a #ffffff
  }
}
