[mgr]
ratio = [2, 4, 3]
show_hidden = true
show_symlink = true

tab_size        = 2
max_width       = 600
max_height      = 900

[preview]
wrap            = "no"
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_delay     = 30
image_filter    = "triangle"
image_quality   = 60
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]
