exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- mako
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- hyprsunset
exec-once = uwsm-app -- swaybg -i ~/Bansuri/defaults/background.jpg -m fill
