#!/bin/bash

MENU="󰖩  WiFi
  Bluetooth
󰕾  Audio
󰄧  Services
󰍛  Processes
  System Info
  Install Package
󰆴  Remove Package"

CHOICE=$(echo "$MENU" | rofi -no-show-icons -dmenu -p "System" -theme-str 'window { width: 12em; }')

case "$CHOICE" in
    *WiFi)
        kitty --title "sysmenu-wifi" nmtui
        ;;
    *Bluetooth)
        kitty --title "sysmenu-bt" bluetoothctl
        ;;
      *Audio)
        pavucontrol
        ;;
    *Services)
        kitty --title "sysmenu-services" bash -c \
            "systemctl --type=service | less"
        ;;
    *Processes*)
        kitty --title "sysmenu-btop" htop
        ;;
    *System\ Info)
        kitty --title "sysmenu-info" fastfetch
        ;;
    *Install\ Package)
        kitty --title "sysmenu-install" install-package
        ;;
    *Remove\ Package)
        kitty --title "sysmenu-remove" remove-package
        ;;
esac

