#!/bin/bash

TERMINAL="${TERMINAL:-xterm}"

MENU="󰖩  WiFi
  Bluetooth
󰕾  Audio
󰄧  Services
󰍛  Processes
  System Info
  Install Package
󰆴  Remove Package"

CHOICE=$(echo "$MENU" | rofi -no-show-icons -dmenu -p "System" -theme-str 'window { width: 12em; }')

term_run() {
    "$TERMINAL" "$@"
}

case "$CHOICE" in
    *WiFi)
        if command -v wlctl >/dev/null 2>&1; then
            term_run --title "sysmenu-wifi" wlctl
        else
            term_run --title "sysmenu-wifi" nmtui
        fi
        ;;
    *Bluetooth)
        term_run --title "sysmenu-bt" bluetoothctl
        ;;
    *Audio)
        pavucontrol
        ;;
    *Services)
        term_run --title "sysmenu-services" bash -c \
            "systemctl --type=service | less"
        ;;
    *Processes*)
        term_run --title "sysmenu-btop" htop
        ;;
    *System\ Info)
        term_run --title "sysmenu-info" fastfetch
        ;;
    *Install\ Package)
        term_run --title "sysmenu-install" install-package
        ;;
    *Remove\ Package)
        term_run --title "sysmenu-remove" remove-package
        ;;
esac

