[general]
import = [
  # "./mocha.toml"
  # "./moonfly.toml"
  "./rosepine.toml"
]

[env]
TERM = "xterm-256color"


[font]
# normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
normal = { family = "Iosevka Nerd Font Propo", style = "Regular" }
size = 17


[window]
padding = { x = 6, y = 6 }
decorations = "None"
dynamic_padding = true
opacity = 0.6

[[keyboard.bindings]]
key = "Insert"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"

[cursor]
style = { shape = "Beam", blinking = "On" }

[bell]
animation = "EaseOut"
