unbind C-b

set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi

# color change
# set -ga terminal-overrides ",xterm-256color:Tc"

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off


# Status bar
set -g status-interval 2
set -g status-style bg=default 
set -g status-justify right
set -g status-left-length 100
set -g status-left "[#S] #{pane_current_path}"
set -g status-right-length 100
set -g status-right ""

# Window list
set -g window-status-current-style bg=#575279
set -g window-status-format " #I #W "
set -g window-status-current-format " #W "

set -g window-status-bell-style fg=#eb6f92,bg=default

# Messages
set -g message-style fg=#e0def4,bg=default
set -g message-command-style fg=#e0def4,bg=default

# Clock
set -g clock-mode-colour "#f6c177"

# Panes
set -g pane-border-style fg=#6e6a86
set -g pane-active-border-style fg=#9ccfd8
set -g pane-border-lines single

##### Behavior #####

# window index reset after window removing
set -g renumber-windows on

# ask for new window name
bind-key c command-prompt -p "window name:" "new-window; rename-window '%%'"

# qoo
set -g escape-time 0
set -g mouse on
set -g repeat-time 1000
set -g history-limit 10000
set-option -g allow-rename off

##### Keybindings #####

bind h split-window -h
bind v split-window -v

bind f resize-pane -Z

# Switch panes with Alt + hjkl (no prefix)
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Switch windows with Alt + Shift + h/l (no prefix)
bind -n M-H previous-window
bind -n M-L next-window

# switch windows using Alt-numbers without prefix
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

